[@Main]

[General UI ]

[*General ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[bg color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bg_color {ini_file(theme,color)}
refresh theme

[bottom button color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bottom_button_color {ini_file(theme,color)}
refresh theme

[click color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme click_color {ini_file(theme,color)}
refresh theme

[default overlay color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme default_overlay_color {ini_file(theme,color)}
refresh theme

[scrollbar color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme scrollbar_color {ini_file(theme,color)}
refresh theme

[scrollbar wall color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme scrollbar_wall_color {ini_file(theme,color)}
refresh theme

[selection bg color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme selection_bg_color {ini_file(theme,color)}
refresh theme

[star color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme star_color {ini_file(theme,color)}
refresh theme

[table bg color ]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme table_bg_color {ini_file(theme,color)}
refresh theme

[unfocused color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme unfocused_color {ini_file(theme,color)}
refresh theme


[*Separators ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[bottom separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bottom_separator_color {ini_file(theme,color)}
refresh theme

[header separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme header_separator_color {ini_file(theme,color)}
refresh theme

[separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme separator_color {ini_file(theme,color)}
refresh theme

[text separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme text_separator_color {ini_file(theme,color)}
refresh theme

[top separator color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme top_separator_color {ini_file(theme,color)}
refresh theme



[*Trackbars ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[trackbar empty color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_empty_color {ini_file(theme,color)}
refresh theme

[trackbar full color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_full_color {ini_file(theme,color)}
refresh theme

[trackbar slider border color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_border_color {ini_file(theme,color)}
refresh theme

[trackbar slider color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_color {ini_file(theme,color)}
refresh theme

[trackbar slider malleable color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_malleable_color {ini_file(theme,color)}
refresh theme