[@RGB]

[General UI]

[*General]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Info]
;mode=table
;background=true
;polling=true
ini_file ./config.ini
'Current'='{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'

[Gap]
;mode=table
;background=false
;gap=15


[bg color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'bg color'

[bottom button color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bottom_button_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'bottom button color'

[click color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme click_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'click color'

[default overlay color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme default_overlay_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'default overlay color'

[scrollbar color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme scrollbar_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'scrollbar color'

[scrollbar wall color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme scrollbar_wall_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'scrollbar wall color'

[selection bg color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme selection_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'selection bg color'

[star color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme star_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'star color'

[table bg color]
;mini=true
ini_file ./config.ini
set-ini-val ./config.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'table bg color'

[unfocused color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme unfocused_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'unfocused color'


[*Separators]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Info]
;mode=table
;background=true
;polling=true
ini_file ./config.ini
'Current'='{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'

[Gap]
;mode=table
;background=false
;gap=15


[bottom separator color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bottom_separator_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'bottom separator color'

[header separator color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme header_separator_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'header separator color'

[separator color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme separator_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'separator color'

[text separator color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme text_separator_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'text separator color'

[top separator color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme top_separator_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'top separator color'



[*Trackbars]

[Red]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme red {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Green]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme green {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme

[Blue]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/rgb.json' name
set-ini-val ./config.ini theme blue {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Info]
;mode=table
;background=true
;polling=true
ini_file ./config.ini
'Current'='{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'

[Gap]
;mode=table
;background=false
;gap=15


[trackbar empty color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_empty_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'trackbar empty color'

[trackbar full color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_full_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'trackbar full color'

[trackbar slider border color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_border_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'trackbar slider border color'

[trackbar slider color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'trackbar slider color'

[trackbar slider malleable color]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme trackbar_slider_malleable_color '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
set-footer '{ini_file(theme,red)}{ini_file(theme,green)}{ini_file(theme,blue)}'
refresh theme
refresh-to 'trackbar slider malleable color'