[@Main]

[Highlights & Logos ]

[*Highlight ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[highlight color 1 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme highlight_color_1 {ini_file(theme,color)}
refresh theme

[highlight color 2 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme highlight_color_2 {ini_file(theme,color)}
refresh theme

[highlight color 3 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme highlight_color_3 {ini_file(theme,color)}
refresh theme

[highlight color 4 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme highlight_color_4 {ini_file(theme,color)}
refresh theme



[*Logo ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[dynamic logo color 1 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme dynamic_logo_color_1 {ini_file(theme,color)}
refresh theme

[dynamic logo color 2 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme dynamic_logo_color_2 {ini_file(theme,color)}
refresh theme

[logo color 1 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme logo_color_1 {ini_file(theme,color)}
refresh theme

[logo color 2 ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme logo_color_2 {ini_file(theme,color)}
refresh theme