[@Main]

[Text & Versions ]

[*General ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val ./config.ini theme color# {json_file_source(*,hex#)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[banner version text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme banner_version_text_color {ini_file(theme,color)}
refresh theme

[default package color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme default_package_color {ini_file(theme,color)}
refresh theme

[default script color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme default_script_color {ini_file(theme,color)}
refresh theme

[text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme text_color {ini_file(theme,color)}
refresh theme



[*Overlays & Packages ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[overlay text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme overlay_text_color {ini_file(theme,color)}
refresh theme

[overlay version text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme overlay_version_text_color {ini_file(theme,color)}
refresh theme

[package text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme package_text_color {ini_file(theme,color)}
refresh theme

[package version text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme package_version_text_color {ini_file(theme,color)}
refresh theme



[*Status & Notifications ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[inprogress text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme inprogress_text_color {ini_file(theme,color)}
refresh theme

[invalid text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme invalid_text_color {ini_file(theme,color)}
refresh theme

[notification text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme notification_text_color {ini_file(theme,color)}
refresh theme

[notification time color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme notification_time_color {ini_file(theme,color)}
refresh theme

[notification title color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme notification_title_color {ini_file(theme,color)}
refresh theme

[off text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme off_text_color {ini_file(theme,color)}
refresh theme

[on text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme on_text_color {ini_file(theme,color)}
refresh theme

[progress color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme progress_color {ini_file(theme,color)}
refresh theme

[warning text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme warning_text_color {ini_file(theme,color)}
refresh theme



[*Ult Overlays & Packages ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[ult overlay text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme ult_overlay_text_color {ini_file(theme,color)}
refresh theme

[ult overlay version text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme ult_overlay_version_text_color {ini_file(theme,color)}
refresh theme

[ult package text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme ult_package_text_color {ini_file(theme,color)}
refresh theme

[ult package version text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme ult_package_version_text_color {ini_file(theme,color)}
refresh theme