[@Main]

[Colors Options]

[*General UI]
;mode=forwarder
package_source './general_ui.ini'


[*Highlights & Logos]
;mode=forwarder
package_source './highlights&logos.ini'


[*Text & Versions]
;mode=forwarder
package_source './text&versions.ini'


[*Widget]
;mode=forwarder
package_source './widget.ini'


[Transparency]

[*Transparency]
;mode=forwarder
package_source './transparency.ini'
exec Transparency
exec 'Transparency' './boot_package.ini'



[@RGB]

[Colors Options]

[*General UI]
;mode=forwarder
package_source './general_ui_rgb.ini'
exec Color
exec 'General UI' './boot_package.ini'


[*Highlights & Logos]
;mode=forwarder
package_source './highlights&logos_rgb.ini'
exec Color
exec 'Highlights & Logos' './boot_package.ini'


[*Text & Versions]
;mode=forwarder
package_source './text&versions_rgb.ini'
exec Color
exec 'Text & Version' './boot_package.ini'


[*Widget]
;mode=forwarder
package_source './widget_rgb.ini'
exec Color
exec 'Widget' './boot_package.ini'


[Transparency]

[*Transparency]
;mode=forwarder
package_source './transparency.ini'
exec Transparency
exec 'Transparency' './boot_package.ini'