[@Main]

[Widget ]

[*Battery ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[battery charging color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_charging_color {ini_file(theme,color)}
refresh theme

[battery color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_color {ini_file(theme,color)}
refresh theme

[battery low color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme battery_low_color {ini_file(theme,color)}
refresh theme



[*General ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[banner version text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme banner_version_text_color {ini_file(theme,color)}
refresh theme

[clock color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme clock_color {ini_file(theme,color)}
refresh theme

[temperature color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme temperature_color {ini_file(theme,color)}
refresh theme

[widget backdrop color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme widget_backdrop_color {ini_file(theme,color)}
refresh theme

[widget border color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme widget_border_color {ini_file(theme,color)}
refresh theme


[*RAM ]

[Presets Colors]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=true
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val ./config.ini theme color {json_file_source(*,hex)}
set-ini-val /config/ultrahand/theme.ini theme table_bg_color {ini_file(theme,color)}
refresh theme


[Gap]
;mode=table
;background=false
;gap=13

[Color Sample]
;mode=table
;background=true

[Gap]
;mode=table
;background=false
;gap=15


[bad ram text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme bad_ram_text_color {ini_file(theme,color)}
refresh theme

[healthy ram text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme healthy_ram_text_color {ini_file(theme,color)}
refresh theme

[neutral ram text color ]
;mini=true
ini_file ./config.ini
set-ini-val /config/ultrahand/theme.ini theme neutral_ram_text_color {ini_file(theme,color)}
refresh theme