[@Updater]

[Updater]

[Gap]
;mode=table
;background=false
;gap=5

[Package Version]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
'Current: {package_version}'='Latest: {ini_file(Release Info,latest_version)}'

[AIO Customizer - Latest]
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/GordyMcGarka/Ultrahand-Customizer/releases?per_page=1 /config/ultrahand/downloads/aio-customizer-api.json
json_file /config/ultrahand/downloads/aio-customizer-api.json
notify-now 'Updating to {ini_file(Release Info,latest_version)} press {R} to stop' 22
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/aio-customizer.zip
notify-now 'Extracting' 24
unzip /config/ultrahand/downloads/aio-customizer.zip '/config/ultrahand/downloads/AIO Customizer/'
notify-now 'Cleaning' 24
exec Backup
exec Cleanup1.0
move '/config/ultrahand/downloads/AIO Customizer/' /switch/.packages/
exec 'Configs Backup' '/switch/.packages/AIO Customizer/configs backup/boot_package.ini'
exec 'Current Release' '/switch/.packages/AIO Customizer/boot_package.ini'
exec 'Release Info' '/switch/.packages/AIO Customizer/boot_package.ini'
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {ini_file(Release Info,latest_version)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 24
delete /config/ultrahand/downloads/*
refresh-to 'AIO Customizer'



[Firmware]

[Update ALL - Latest]
try:
exec 'Atmosphere - Latest' ./updater_cleanup.ini
exec 'Firmware - Latest' ./updater_cleanup.ini
exec 'Hekate - Latest' ./updater_cleanup.ini
exec 'Sys-Patch - Latest' ./updater_cleanup.ini

[Gap]
;mode=table
;background=false
;gap=5



[Atmosphere Version]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
'Current: {ams_version}'='Latest: {ini_file(Firmware Release Info,atmosphere)}'

[Atmosphere - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/Atmosphere-NX/Atmosphere/releases?per_page=1 /config/ultrahand/downloads/atmosphere-api.json
json_file /config/ultrahand/downloads/atmosphere-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 24
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/atmosphere.zip
download {json_file(0,assets,1,browser_download_url)} '/firmware update/bootloader/payloads/'
notify-now 'Extracting' 24
unzip /config/ultrahand/downloads/atmosphere.zip '/firmware update/'
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 24
delete /config/ultrahand/downloads/*
refresh-to 'Atmosphere'

[Gap]
;mode=table
;background=false
;gap=5



[Firmware Version]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
'Current: {hos_version}'='Latest: {ini_file(Firmware Release Info,firmware)}'

[Firmware - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/THZoria/NX_Firmware/releases?per_page=page=1 /config/ultrahand/downloads/firmware-api.json
json_file /config/ultrahand/downloads/firmware-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 24
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/firmware.zip
notify-now 'Extracting' 24
unzip /config/ultrahand/downloads/firmware.zip /Firmware_{json_file(0,tag_name)}/
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 24
delete /config/ultrahand/downloads/*
refresh-to 'Firmware'



[Hekate Version]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
''='Latest: {ini_file(Firmware Release Info,hekate)}'

[Hekate - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/CTCaer/hekate/releases?per_page=1 /config/ultrahand/downloads/hekate-api.json
json_file /config/ultrahand/downloads/hekate-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 24
download {json_file(0,assets,1,browser_download_url)} /config/ultrahand/downloads/hekate.zip
notify-now 'Extracting' 24
unzip /config/ultrahand/downloads/hekate.zip '/firmware update/'
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 24
delete /config/ultrahand/downloads/*
refresh-to 'Hekate'



[Sys-Patch Version]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
''='Latest: {ini_file(Firmware Release Info,sys-patch)}'

[Sys-Patch - Latest]
;mini=true
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
download https://api.github.com/repos/impeeza/sys-patch/releases?per_page=1 /config/ultrahand/downloads/sys-patch-api.json
json_file /config/ultrahand/downloads/sys-patch-api.json
notify-now 'Updating to {json_file(0,tag_name)} press {R} to stop' 24
download {json_file(0,assets,0,browser_download_url)} /config/ultrahand/downloads/sys-patch.zip
notify-now 'Extracting' 24
unzip /config/ultrahand/downloads/sys-patch.zip '/firmware update/'
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Updated to {json_file(0,tag_name)} took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 24
delete /config/ultrahand/downloads/*
refresh-to 'Sys-Patch'



[@Cleanup]

[Delete/Download Assets]

[*Boot Customization]
;mode=forwarder
package_source './boot.ini'



[*Musics Customization]
;mode=forwarder
package_source './music.ini'



[*Backgrounds & Wallpapers]
;mode=forwarder
package_source './b_w.ini'



[Update ALL Assets]

[Assets Version]
;mode=table
;polling=false
;background=false
;gap=15
ini_file ./config.ini
'Current: {ini_file(Assets Info,current_version)}'='Latest: {ini_file(Assets Info,latest_version)}'

[Update ALL Assets]
try:
ini_file ./config.ini
set-ini-val ./config.ini Timer start {timestamp(%s.%f)}
'{ini_file(Disable ALL Assets,notification)}' 'Disabling ALL Assets' 24
'{ini_file(Disable ALL Assets,action)}' 'Disable Bootlogo' '/switch/.packages/AIO Customizer/ini/boot customization/boot_package.ini'
'{ini_file(Disable ALL Assets,action)}' 'Disable Bootsound' '/switch/.packages/AIO Customizer/ini/boot customization/boot_package.ini'
'{ini_file(Disable ALL Assets,action)}' 'Disable Background' '/switch/.packages/AIO Customizer/ini/hekate customization/boot_package.ini'
'{ini_file(Disable ALL Assets,action)}' 'Disable App Store Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
'{ini_file(Disable ALL Assets,action)}' 'Disable Sphaira Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
'{ini_file(Disable ALL Assets,action)}' 'Disable Home Menu Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
'{ini_file(Disable ALL Assets,action)}' 'Disable Wallpaper' '/switch/.packages/AIO Customizer/ini/theme customization/boot_package.ini'
'{ini_file(Delete ALL Assets,notification)}' 'Deleting ALL Assets' 24
'{ini_file(Delete ALL Assets,action)}' '/switch/.packages/AIO Customizer/background/'
'{ini_file(Delete ALL Assets,action)}' '/switch/.packages/AIO Customizer/bootlogo/'
'{ini_file(Delete ALL Assets,action)}' '/switch/.packages/AIO Customizer/bootsound/'
'{ini_file(Delete ALL Assets,action)}' '/switch/.packages/AIO Customizer/music/'
'{ini_file(Delete ALL Assets,action)}' '/switch/.packages/AIO Customizer/splashscreen/'
'{ini_file(Delete ALL Assets,action)}' '/switch/.packages/AIO Customizer/wallpaper/'
notify-now 'Updating ALL Assets press {R} to stop' 22
download https://github.com/GordyMcGarka/AIO-Customizer/releases/latest/download/assets.zip /config/ultrahand/downloads/
notify-now 'Extracting ALL' 24
unzip /config/ultrahand/downloads/assets.zip /
ini_file ./RELEASE.ini
set-ini-val ./config.ini 'Assets Info' current_version '{ini_file(Assets Info,current_version)}'
delete ./RELEASE.ini
ini_file ./config.ini
exec 'Boot Customization' '/switch/.packages/AIO Customizer/ini/boot customization/boot_package.ini'
exec 'Hekate Customization' '/switch/.packages/AIO Customizer/ini/hekate customization/boot_package.ini'
exec 'Wallpaper' '/switch/.packages/AIO Customizer/ini/theme customization/boot_package.ini'
exec 'Music' '/switch/.packages/AIO Customizer/ini/music/boot_package.ini'
delete /config/ultrahand/downloads/*
set-ini-val ./config.ini Timer stop {timestamp(%s.%f)}
notify-now 'Assets Downloaded, took {math({ini_file(Timer,stop)}-{ini_file(Timer,start)})}s' 24
refresh-to 'Update ALL Assets'

[Gap]
;mode=table
;background=false
;gap=5



[Info]
;mode=table
;background=false
;gap=15
'When updating all assets{DOWN_ARROW}:'=''

[Disable ALL Assets]
;mini=true
;mode=toggle?off
on:
    set-ini-val ./config.ini 'Disable ALL Assets' action exec
    set-ini-val ./config.ini 'Disable ALL Assets' notification notify-now
off:
    remove-ini-key ./config.ini 'Disable ALL Assets' action
    remove-ini-key ./config.ini 'Disable ALL Assets' notification



[Delete ALL Assets]
;mini=true
;mode=toggle?off
on:
    set-ini-val ./config.ini 'Delete ALL Assets' action delete
    set-ini-val ./config.ini 'Delete ALL Assets' notification notify-now
off:
    remove-ini-key ./config.ini 'Delete ALL Assets' action
    remove-ini-key ./config.ini 'Delete ALL Assets' notification
