;title='RAM Patch'
;creator=CatcherITGF
;version=1.0.0
;about='Switch between default 4GB boot and GB RAM boot'
;color=blue
;show_widget=true

[Default]
;hold=true
cp './Default/payload.bin' /payload.bin
cp './Default/update.bin' /bootloader/update.bin
cp './Default/reboot_payload.bin' /atmosphere/reboot_payload.bin
cp './Default/hekate_ipl.ini' /bootloader/hekate_ipl.ini
cp './Default/no_oc.ini' /bootloader/ini/no_oc.ini
reboot

[8GB]
;hold=true
cp './8GB/hekate_ctcaer_6.5.2__ram8GB.bin' /payload.bin
cp './8GB/hekate_ctcaer_6.5.2__ram8GB.bin' /bootloader/update.bin
cp './8GB/hekate_ctcaer_6.5.2__ram8GB.bin' /atmosphere/reboot_payload.bin
cp './8GB/hekate_ipl.ini' /bootloader/hekate_ipl.ini
cp './8GB/no_oc.ini' /bootloader/ini/no_oc.ini
reboot
