[@TC Page]

[Colors Options]

[*Theme Customizer]
;mode=forwarder
package_source './colors options/theme_customizer.ini'


[Gap]
;mode=table
;background=false
;gap=15

[Header]
;color=
;mode=table
;background=false
;header_indent=true
;polling=true
ini_file ./config.ini
'Selected:' = '{ini_file(preset,current)}'



[*Select Preset]
;mini=true
file_source '/switch/.packages/AIO Customizer/preset/*.ini'
set-ini-val ./config.ini preset current {file_name}
back

[Gap]
;mode=table
;background=false
;gap=5



[Info]
;mode=table
;background=false
;gap=15
'Presets Location'='./preset/'



[Default Preset]
;mini=true
copy '/switch/.packages/AIO Customizer/preset/default/default.ini' /config/ultrahand/theme.ini
refresh theme



[*Custom Preset]
;mini=true
;grouping=split
file_source '/switch/.packages/AIO Customizer/preset/custom/*.ini'
copy {file_source} /config/ultrahand/theme.ini
set-ini-val ./config.ini preset current {file_name}
refresh theme
back



[*Restore Preset]
;mini=true
;grouping=split
file_source '/switch/.packages/AIO Customizer/preset/*.ini'
copy {file_source} /config/ultrahand/theme.ini
set-ini-val ./config.ini preset current {file_name}
refresh theme
back



[*Rename Selected To]
;mini=true
list_file_source '/switch/.packages/AIO Customizer/txt/preset_name.txt'
ini_file ./config.ini
move '/switch/.packages/AIO Customizer/preset/{ini_file(preset,current)}.ini' '/switch/.packages/AIO Customizer/preset/{list_file_source(*)}.ini'
set-ini-val ./config.ini preset current {list_file_source(*)}
back



[*Delete Preset]
;mini=true
file_source '/switch/.packages/AIO Customizer/preset/*.ini'
delete {file_source}



[*Overwrite Backup]
;mini=true
file_source '/switch/.packages/AIO Customizer/preset/*.ini'
copy /config/ultrahand/theme.ini {file_source}
set-ini-val ./config.ini preset current {file_name}
back



[Save Preset]
;mini=true
copy /config/ultrahand/theme.ini '/switch/.packages/AIO Customizer/preset/{timestamp(%Y.%m.%d_[%H-%M-%S])}.ini'
set-ini-val ./config.ini preset current {timestamp(%Y.%m.%d_[%H-%M-%S])}



[@More Options]

[Package Title Color]

[Wallpapers]

[Info]
;mode=table
;background=false
;gap=15
'Wallpapers Location'='./wallpaper/'


[Disable Wallpaper]
;mini=true
ini_file ./config.ini
move /config/ultrahand/wallpaper.rgba '/switch/.packages/AIO Customizer/wallpaper/{ini_file(*Wallpaper,footer)}.rgba'
delete '/switch/.packages/AIO Customizer/wallpaper/Disabled.rgba'
remove-ini-key ./config.ini *Wallpaper footer
refresh wallpaper
refresh-to 'Disable Wallpaper'


[*Wallpaper]
;mini=true
;mode=option
;footer=Disabled
ini_file ./config.ini
file_source '/switch/.packages/AIO Customizer/wallpaper/*.rgba'
move /config/ultrahand/wallpaper.rgba '/switch/.packages/AIO Customizer/wallpaper/{ini_file(*Wallpaper,footer)}.rgba'
delete '/switch/.packages/AIO Customizer/wallpaper/Disabled.rgba'
move {file_source} /config/ultrahand/wallpaper.rgba
set-footer {file_name}
refresh wallpaper
refresh-to *Wallpaper



[Package Title Color]
;mode=named_step_trackbar
;unlocked=true
;on_every_tick=false
ini_file ./config.ini
json_file_source '/switch/.packages/AIO Customizer/json/sort_by.json' name
set-ini-val '/switch/.packages/AIO Customizer/package.ini' 'Header' ;color {json_file_source(*,hex#)}
set-ini-val '/switch/.packages/AIO Customizer/ini/theme customization/theme_customizer.ini' 'Header' ;color {json_file_source(*,hex#)}
refresh-to 'Package Title Color'



[Sort By]

[*Sort By]
;mini=true
[A  Z]
;mini=true
copy '/switch/.packages/AIO Customizer/json/a_to_z.json' '/switch/.packages/AIO Customizer/json/sort_by.json'
set-ini-val ./config.ini '*Sort By' footer 'A  Z'
back


[Z  A]
;mini=true
copy '/switch/.packages/AIO Customizer/json/z_to_a.json' '/switch/.packages/AIO Customizer/json/sort_by.json'
set-ini-val ./config.ini '*Sort By' footer 'Z  A'
back


[Cold  Hot]
;mini=true
copy '/switch/.packages/AIO Customizer/json/cold_to_hot.json' '/switch/.packages/AIO Customizer/json/sort_by.json'
set-ini-val ./config.ini '*Sort By' footer 'Cold  Hot'
back


[Hot  Cold]
;mini=true
copy '/switch/.packages/AIO Customizer/json/hot_to_cold.json' '/switch/.packages/AIO Customizer/json/sort_by.json'
set-ini-val ./config.ini '*Sort By' footer 'Hot  Cold'
back



[Invert Bg Click Color]

[Invert Bg Click Color]
;mini=true
;mode=toggle?off
on:
    set-ini-val /config/ultrahand/theme.ini theme invert_bg_click_color true
off:
    set-ini-val /config/ultrahand/theme.ini theme invert_bg_click_color false