name: build
on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # It's needed for git-restore-mtime
      - name: Reset directories timestamp # Workaround for https://github.com/MestreLion/git-tools/issues/47
        run: find . -mindepth 1 -type d -not -iwholename '*.git*' -exec touch -t 197001010000 {} \;
      - name: Restore files timestamp
        uses: chetan/git-restore-mtime-action@v2 # Restore files original modification time to have deterministic zip bundles
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: "Install FPSLocker patches"
        working-directory: ./Sources/NXVenom
        run: curl -L https://github.com/masagrator/FPSLocker-Warehouse/archive/refs/heads/v3.1.zip > patches.zip && unzip patches.zip && rm -rf SaltySD/plugins/FPSLocker/patches && cp -r FPSLocker-Warehouse-3.1/SaltySD/plugins SaltySD/ && rm -rf FPSLocker-Warehouse-3.1 && rm -rf patches.zip
      - name: "Compile NXVenom"
        working-directory: ./Sources/NXVenom
        run: rm -rf ../../NXVenom.zip && zip -qqrX ../../NXVenom.zip ./
      - name: "Compile AIO"
        working-directory: ./Sources/AIO
        run: rm -rf ../../AIO.zip && zip -qqrX ../../AIO.zip ./
      - name: "Compile SC Wizard"
        working-directory: ./Sources/NXVenom
        run: rm -rf ../../SC Wizard.zip && zip -qqrX "../../SC Wizard.zip" "./switch/.packages/SC Wizard" ./switch/.overlays/ovlmenu.ovl
      - name: "Compile packages"
        working-directory: ./Sources/Tools/Uberhand Packages
        run: rm -rf "RAM Patch.zip" && zip -qqrX "RAM Patch.zip" "RAM Patch" && rm -rf "TOTK UltraCam.zip" && zip -qqrX "TOTK UltraCam.zip" "TOTK UltraCam"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build: Compile Bundle"
          file_pattern: "*.zip"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: false
          files: NXVenom.zip
