name: build
on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # It's needed for git-restore-mtime
      - name: Reset directories timestamp # Workaround for https://github.com/MestreLion/git-tools/issues/47
        run: find . -mindepth 1 -type d -not -iwholename '*.git*' -exec touch -t 197001010000 {} \;
      - name: Restore files timestamp
        uses: chetan/git-restore-mtime-action@v2 # Restore files original modification time to have deterministic zip bundles
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: "Install FPSLocker patches"
        run: make install-fpslocker-patches
      - name: "Compile NXVenom"
        run: make build-nxvenom
      - name: "Compile AIO"
        run: make build-aio
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build: Compile Bundle"
          file_pattern: "AIO.zip NXVenom.zip"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: false
          files: NXVenom.zip
